services:
  koofr-watch:
    ports:
      - "4447:4447"
    environment:
      PORT: "4447"
      WEBHOOK_URL_2: https://529fe195d8ee1d50e6c4f5ff3bcc5ecc.m.pipedream.net
      WEBHOOK_URL_1: $WEBHOOK_URL_1

  grafana:
    image: bitnami/grafana:latest
    ports:
      - "0.0.0.0:4448:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      TZ: CET
    depends_on:
      - prometheus

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    environment:
      TZ: CET
    ports:
      - "0.0.0.0:4449:9090"
    configs:
      - source: prometheus_config
        target: /opt/bitnami/prometheus/conf/prometheus.yml
    depends_on:
      - koofr-watch

configs:
  prometheus_config:
    content: |
      scrape_configs:
        - job_name: 'koofr-watch'
          metrics_path: 'metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['koofr-watch:4447']
        - job_name: 'koofr-watch-host'
          metrics_path: 'metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['host.docker.internal:4446']



